version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - revive
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: /*.go
        text: 'package-comments: should have a package comment'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netboxlabs/opentelemetry-infinity/)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$