name: otlpinf-main

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Generate ref tag (latest)
        run: |
          echo "REF_TAG=latest" >> $GITHUB_ENV

      - name: get otelcol-contrib
        run: make getotelcol

      - name: Build binnary (go build only)
        run: make build

      - name: Unit Tests with Coverage
        run: make testcov
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  package:
    if: ${{ github.event_name != 'pull_request' }} 
    needs: [ pre-build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate ref tag (latest)
        run: |
          echo "REF_TAG=latest" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      - name: Build opentelemetry-infinity container
        shell: bash
        run: |
           make container

      - name: Push opentelemetry-infinity container
        run: |
          docker push -a netboxlabs/opentelemetry-infinity
